stages:
  - build_test
  - github-mirror

x86_64_linux_build_test:
  stage: build_test
  script:
    - make dirs
    - make
  tags:
    - x86_64
    - linux
    - OpenCL
  allow_failure: false

arm_linux_build_test:
  stage: build_test
  script:
    - make dirs
    - make
  tags:
    - ARM
    - linux
    - OpenCL
  allow_failure: false

github-push:
  stage: github-mirror
  script:
    - git remote add github git@github.com:yeonzi/BMP-Super-Resolution.git
    - git push github develop --force
  tags:
    - deploy
    - github
    - git
  allow_failure: true
