stages:
  - github-mirror

github-push:
  stage: github-mirror
  script:
    - git pull origin develop
    - git remote add github git@github.com:yeonzi/BMP-Super-Resolution.git
    - git push github develop --force
  tags:
    - deploy
    - github
    - git
  allow_failure: true
