stages:
  - build_test
  - github-mirror

x86_64-w64-mingw32_build_test:
  stage: build_test
  script:
    - mkdir lib64
    - wget http://101.200.150.73/libOpenCL.a -O ./lib64/libOpenCL.a
    - mingw64-make dirs
    - mingw64-make LDFLAGS=-Llib64\ -lOpenCL
  tags:
    - x86_64-w64-mingw32
    - linux
    - OpenCL
  allow_failure: false

x86_64_linux_build_test:
  stage: build_test
  script:
    - make dirs
    - make
  tags:
    - x86_64
    - linux
    - OpenCL
  allow_failure: false

arm_linux_build_test:
  stage: build_test
  script:
    - make dirs
    - make
  tags:
    - ARM
    - linux
    - OpenCL
  allow_failure: false

github-push:
  stage: github-mirror
  script:
    - git pull origin gpu-mem-linear
    - git checkout gpu-mem-linear
    - git remote add github git@github.com:yeonzi/BMP-Super-Resolution.git
    - git push github gpu-mem-linear --force
  tags:
    - deploy
    - github
    - git
  allow_failure: true
